# Generated by Django 4.1.7 on 2023-04-08 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProfesional',
            fields=[
                ('id_categoria_profesional', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreCatPro', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Conocimiento',
            fields=[
                ('id_conocimiento', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id_curriculum', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreEmp', models.CharField(max_length=100)),
                ('correoEmp', models.EmailField(max_length=254)),
                ('rucEmp', models.CharField(max_length=11)),
                ('userEmp', models.CharField(max_length=100)),
                ('passwordEmp', models.CharField(max_length=50)),
                ('url_sitioEmp', models.URLField()),
                ('profileEmp', models.ImageField(blank=True, default='profiles/profileHitler.jpeg', upload_to='profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Formacion',
            fields=[
                ('id_formacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_institucion', models.CharField(max_length=255)),
                ('grado_titulo', models.CharField(max_length=255)),
                ('carrera', models.CharField(max_length=255)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id_habilidad', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id_idioma', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id_post', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('requerimientos', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_estatus', models.BigAutoField(primary_key=True, serialize=False)),
                ('grado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEmpresa',
            fields=[
                ('id_tipo_empresa', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreTipEmp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombresUs', models.CharField(max_length=100)),
                ('correoUs', models.EmailField(max_length=254)),
                ('dniUs', models.CharField(max_length=8)),
                ('sexoUs', models.CharField(max_length=1)),
                ('userUs', models.CharField(max_length=100)),
                ('passwordUs', models.CharField(max_length=50)),
                ('profileUser', models.ImageField(blank=True, default='profiles/profileHitler.jpeg', upload_to='profiles')),
                ('id_categoria_profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kang.categoriaprofesional')),
                ('id_estatusUs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kang.status')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kang.post')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kang.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PostDetalle',
            fields=[
                ('id_post_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kang.empresa')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kang.post')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='id_estatusEmp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kang.status'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='id_tipo_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kang.tipoempresa'),
        ),
        migrations.CreateModel(
            name='CurriculumIdiomas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kang.curriculum')),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kang.idioma')),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumHabilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kang.curriculum')),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kang.habilidad')),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumFormacionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kang.curriculum')),
                ('formacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kang.formacion')),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumConocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conocimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kang.conocimiento')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kang.curriculum')),
            ],
        ),
        migrations.AddField(
            model_name='curriculum',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kang.usuario'),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_administrador', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombresAdm', models.CharField(max_length=100)),
                ('correoAdm', models.EmailField(max_length=254)),
                ('dniAdm', models.CharField(max_length=8)),
                ('sexoAdm', models.CharField(max_length=1)),
                ('userAdm', models.CharField(max_length=100)),
                ('passwordAdm', models.CharField(max_length=50)),
                ('id_estatusAdm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kang.status')),
            ],
        ),
    ]
