# Generated by Django 4.1.7 on 2023-04-14 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ayuda',
            fields=[
                ('id_ayuda', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_persona', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=9)),
                ('correo', models.EmailField(max_length=254)),
                ('problema', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaProfesional',
            fields=[
                ('id_categoria_profesional', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreCatPro', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreEmp', models.CharField(max_length=100)),
                ('correoEmp', models.EmailField(max_length=254)),
                ('rucEmp', models.CharField(max_length=11)),
                ('userEmp', models.CharField(max_length=100)),
                ('passwordEmp', models.CharField(max_length=50)),
                ('url_sitioEmp', models.URLField()),
                ('profileEmp', models.ImageField(blank=True, default='profiles/defaultProfile.jpg', upload_to='profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id_post', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('requerimientos', models.CharField(max_length=500)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kang.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_estatus', models.BigAutoField(primary_key=True, serialize=False)),
                ('grado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEmpresa',
            fields=[
                ('id_tipo_empresa', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreTipEmp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombresUs', models.CharField(max_length=100)),
                ('correoUs', models.EmailField(max_length=254)),
                ('dniUs', models.CharField(max_length=8)),
                ('sexoUs', models.CharField(max_length=1)),
                ('telefono', models.CharField(max_length=9)),
                ('direccion', models.TextField()),
                ('userUs', models.CharField(max_length=100)),
                ('passwordUs', models.CharField(max_length=50)),
                ('profileUser', models.ImageField(blank=True, default='profiles/defaultProfile.jpg', upload_to='profiles')),
                ('id_categoria_profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kang.categoriaprofesional')),
                ('id_estatusUs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kang.status')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kang.post')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kang.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PostDetalle',
            fields=[
                ('id_post_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kang.post')),
            ],
        ),
        migrations.CreateModel(
            name='FormacionAcademica',
            fields=[
                ('id_formacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreInstitucion', models.CharField(max_length=200)),
                ('grado_titulo', models.CharField(max_length=200)),
                ('carrera', models.CharField(max_length=200)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kang.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id_experiencia', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=200)),
                ('cargo_ocupado', models.CharField(max_length=200)),
                ('tarea_realizadas', models.CharField(max_length=200)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kang.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='id_estatusEmp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kang.status'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='id_tipo_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kang.tipoempresa'),
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id_curriculum', models.BigAutoField(primary_key=True, serialize=False)),
                ('perfil_profesional', models.TextField()),
                ('idiomas', models.CharField(max_length=200)),
                ('conocimientos', models.CharField(max_length=200)),
                ('habilidades', models.CharField(max_length=200)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kang.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_administrador', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombresAdm', models.CharField(max_length=100)),
                ('correoAdm', models.EmailField(max_length=254)),
                ('dniAdm', models.CharField(max_length=8)),
                ('sexoAdm', models.CharField(max_length=1)),
                ('userAdm', models.CharField(max_length=100)),
                ('passwordAdm', models.CharField(max_length=50)),
                ('id_estatusAdm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kang.status')),
            ],
        ),
    ]
