# Generated by Django 4.1.7 on 2023-04-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='profileEmp',
            field=models.ImageField(blank=True, default='profiles/defaultProfile.jpg', upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='profileUser',
            field=models.ImageField(blank=True, default='profiles/defaultProfile.jpg', upload_to='profiles'),
        ),
    ]
