# Generated by Django 4.1.7 on 2023-04-09 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_kang', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='id_experiencia',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='id_formacion',
        ),
    ]
